// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TalentBay.Models;

#nullable disable

namespace TalentBay.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity<User>(entity =>
            {
                entity.Property(e => e.Id)
                    .HasColumnType("int")
                    .UseIdentityColumn();

                entity.Property(e => e.Username)
                    .IsRequired()
                    .HasColumnType("VarChar(20)");

                entity.Property(e => e.Email)
                    .IsRequired()
                    .HasColumnType("VarChar(50)");

                entity.Property(e => e.Password)
                    .IsRequired()
                    .HasColumnType("VarChar(20)");

                entity.Property(e => e.ConfirmPassword)
                    .IsRequired()
                    .HasColumnType("VarChar(20)");

                entity.Property(e => e.IsStudent)
                    .HasColumnType("bit")
                    .IsRequired();

                entity.HasKey(e => e.Id);
            });
#pragma warning restore 612, 618
        }
    }
}
